// species.js — Catálogo de especies de abejas meliponas (abejas sin aguijón)
// Información general de manejo. No reemplaza el criterio de un meliponicultor experimentado.

const ESPECIES = [
  {
    id: 'yatei',
    nombre: 'Yateí',
    nombreCientifico: 'Tetragonisca angustula / T. fiebrigi',
    otrosNombres: ['Angelita', 'Rubita', 'Virginita'],
    temperamento: 'muy_docil',
    tamanoColonia: 'pequeña (2.000–5.000 obreras)',
    produccionMiel: 'baja (0,5–1,5 L/año)',
    intervaloRevisionDias: 45,
    tempIdealMin: 22,
    tempIdealMax: 34,
    resistenciaFrio: 'baja',
    resistenciaCalor: 'media',
    dificultad: 'principiante',
    entrada: 'Túnel de cera ("corneta") con guardianas suspendidas en el aire, característico de la especie — no confundir con daño.',
    tips: [
      'Ideal para empezar: casi no se defiende, solo algunas guardianas revolotean cerca de la cara sin picar ni morder.',
      'Coloniza espacios pequeños; no fuerces cambios de caja grandes de una sola vez.',
      'Muy sensible al frío — por debajo de 15°C la actividad de vuelo cae mucho, protegé la caja del viento sur.',
      'Producción de miel baja pero de gran valor (uso medicinal tradicional); no cosechar más de 1–2 veces al año.',
      'Es de las especies con mayor riesgo de pillaje (robo de otras colonias) en época de seca — mantené la piquera reducida si notás peleas en la entrada.',
    ],
  },
  {
    id: 'mandaguari',
    nombreCientifico: 'Scaptotrigona spp.',
    nombre: 'Mandaguari / Tubuna',
    otrosNombres: ['Mandaçaia chica', 'Tubuna'],
    temperamento: 'defensiva',
    tamanoColonia: 'grande (10.000–20.000 obreras)',
    produccionMiel: 'alta (2–4 L/año)',
    intervaloRevisionDias: 30,
    tempIdealMin: 24,
    tempIdealMax: 34,
    resistenciaFrio: 'media',
    resistenciaCalor: 'alta',
    dificultad: 'intermedio',
    entrada: 'Piquera en forma de embudo de cerumen oscuro, a veces con pequeños "cuernos".',
    tips: [
      'Se defiende enredándose en el pelo y la ropa; no pica pero muerde — usá velo y evitá revisar con el pelo suelto.',
      'Se pone más agresiva en días nublados o antes de tormenta: revisá solo con sol franco.',
      'Buena productora de miel y propóleo; tolera bien revisiones más frecuentes que la yateí.',
      'Coloniza rápido cajas nuevas — buena candidata para multiplicación por división.',
      'Vuela rápido y en línea recta desde la piquera: cuidado al pararte justo enfrente.',
    ],
  },
  {
    id: 'guaraipo',
    nombreCientifico: 'Melipona quadrifasciata / M. bicolor',
    nombre: 'Guaraipo / Manduri grande',
    otrosNombres: ['Manduri'],
    temperamento: 'docil',
    tamanoColonia: 'mediana-grande (3.000–8.000 obreras)',
    produccionMiel: 'alta (2–5 L/año)',
    intervaloRevisionDias: 40,
    tempIdealMin: 20,
    tempIdealMax: 32,
    resistenciaFrio: 'media',
    resistenciaCalor: 'media',
    dificultad: 'intermedio',
    entrada: 'Piquera amplia y visible, a veces con pequeño alero de cerumen.',
    tips: [
      'Son abejas más grandes (parecidas a Apis en tamaño); manejo tranquilo si se hace con movimientos lentos.',
      'Necesitan cajas de mayor volumen que la yateí — no reduzcas demasiado el espacio interno.',
      'Buenas productoras, pero más sensibles al frío intenso que las especies de cajas chicas: reforzá aislación en invierno.',
      'La división de colonias suele requerir más experiencia porque forman menos realeras que otras especies — hacelo en temporada cálida con buena floración.',
    ],
  },
  {
    id: 'mirim',
    nombreCientifico: 'Plebeia spp.',
    nombre: 'Mirim / Moro-boi mirim',
    otrosNombres: ['Mirí'],
    temperamento: 'muy_docil',
    tamanoColonia: 'pequeña (1.000–3.000 obreras)',
    produccionMiel: 'muy baja (200–500 ml/año)',
    intervaloRevisionDias: 50,
    tempIdealMin: 22,
    tempIdealMax: 33,
    resistenciaFrio: 'baja',
    resistenciaCalor: 'media',
    dificultad: 'principiante',
    entrada: 'Piquera diminuta, a veces apenas un orificio en la madera.',
    tips: [
      'Totalmente inofensivas; ideales para tener cerca de la casa o para mostrar a niños con supervisión.',
      'Producen muy poca miel — se manejan más por polinización y conservación que por cosecha.',
      'Colonias chicas se debilitan fácil: evitá revisiones muy frecuentes o invasivas.',
      'Muy sensibles a corrientes de aire frío; ubicación protegida es clave.',
    ],
  },
  {
    id: 'irapua',
    nombreCientifico: 'Trigona spinipes',
    nombre: 'Irapuã',
    otrosNombres: [],
    temperamento: 'agresiva',
    tamanoColonia: 'muy grande (10.000–100.000+ obreras)',
    produccionMiel: 'baja y de sabor fuerte (poco apreciada)',
    intervaloRevisionDias: 60,
    tempIdealMin: 20,
    tempIdealMax: 36,
    resistenciaFrio: 'alta',
    resistenciaCalor: 'alta',
    dificultad: 'no recomendada para principiantes',
    entrada: 'Nido expuesto de cerumen oscuro, a menudo sobre árboles, no en cajas racionales.',
    tips: [
      'Especie muy defensiva: muerde en grupo y puede arrancar pelo o vello; requiere mucha experiencia.',
      'No suele manejarse en cajas racionales como las demás — se aprovecha sobre todo el propóleo.',
      'Puede ser competidora agresiva de otras colonias del meliponario: mantené distancia si hay nidos silvestres cerca.',
      'Se recomienda solo para meliponicultores avanzados o con fines de investigación/propóleo.',
    ],
  },
  {
    id: 'bocasapo',
    nombreCientifico: 'Frieseomelitta spp.',
    nombre: 'Boca de sapo',
    otrosNombres: ['Moro-boi'],
    temperamento: 'muy_docil',
    tamanoColonia: 'pequeña-mediana (2.000–6.000 obreras)',
    produccionMiel: 'baja (0,5–1 L/año)',
    intervaloRevisionDias: 45,
    tempIdealMin: 22,
    tempIdealMax: 33,
    resistenciaFrio: 'baja',
    resistenciaCalor: 'media',
    dificultad: 'principiante',
    entrada: 'Piquera aplanada y ancha en forma de "boca de sapo", de cerumen blando.',
    tips: [
      'Extremadamente mansa, casi no reacciona a la revisión.',
      'La piquera blanda se daña fácil — evitá golpes o presión sobre la entrada al mover la caja.',
      'Buena opción para meliponarios cerca de zonas de tránsito de personas por su nula defensividad.',
    ],
  },
  {
    id: 'mandurimirim',
    nombreCientifico: 'Nannotrigona spp.',
    nombre: 'Mandurí chica',
    otrosNombres: ['Mandurí'],
    temperamento: 'docil',
    tamanoColonia: 'pequeña (1.500–4.000 obreras)',
    produccionMiel: 'baja (0,5–1 L/año)',
    intervaloRevisionDias: 45,
    tempIdealMin: 22,
    tempIdealMax: 34,
    resistenciaFrio: 'baja',
    resistenciaCalor: 'media',
    dificultad: 'principiante',
    entrada: 'Piquera pequeña y bien camuflada, a veces con manchas de resina alrededor.',
    tips: [
      'Piquera muy discreta — marcá bien la caja para no perderla de vista en el meliponario.',
      'Buena polinizadora de flores pequeñas del monte chaqueño.',
      'Manejo similar a la yateí; buena segunda especie para quien ya tiene experiencia con esa.',
    ],
  },
];

// Recomendaciones generales de manejo aplicables a toda la meliponicultura,
// independientemente de la especie.
const TIPS_GENERALES = [
  'El mejor horario para revisar es de media mañana a media tarde (10:00–15:00), cuando la mayoría de las pecoreadoras está afuera y la colonia está más calma.',
  'Evitá abrir las cajas en días fríos (menos de 18°C), lluviosos, muy ventosos o justo antes de una tormenta: el frío y la humedad entran al nido y pueden dañar cría y reservas.',
  'Las meliponas no necesitan humo como las abejas Apis — el humo las estresa más de lo que ayuda. Movimientos lentos y suaves son la mejor herramienta.',
  'Cuanto menos tiempo esté la caja abierta, mejor. Planificá antes qué vas a hacer (foto, cosecha, revisión) para minimizar el tiempo de exposición.',
  'Llevá siempre un registro de cosecha por caja: mismo lugar, misma especie, distinta producción — la bitácora ayuda a detectar qué manejo funciona mejor.',
  'La cosecha de miel se hace rompiendo los potes de miel (no los de cría) y dejando escurrir o extrayendo con jeringa; la de propóleo raspando con cuidado sin exponer demasiado la cría.',
  'Un meliponario necesita fuente de agua cercana, sobre todo en época seca y calurosa del Chaco — un bebedero con piedras evita que se ahoguen.',
  'Separá las cajas al menos 50 cm entre sí y orientá las piqueras evitando el sol directo de la tarde y los vientos dominantes fríos.',
  'La principal plaga a vigilar es la mosca fórida (Pseudohypocera kerteszi): revisá el piso y alrededores de la caja por larvas blancas si notás mal olor o debilidad de la colonia.',
  'Las hormigas son depredadoras frecuentes de cría y reservas — usá barreras de agua o grasa en las patas del soporte de la caja.',
  'La división de colonias (multiplicación) se hace mejor en época cálida con buena floración, cuando la colonia madre tiene suficiente cría operculada y reservas para repartir con la caja hija.',
  'Después de una división, evitá revisar la caja hija por al menos 15–20 días para no estresar a la nueva reina en formación.',
];

if (typeof module !== 'undefined') {
  module.exports = { ESPECIES, TIPS_GENERALES };
}
